### ISSUE TITLE
Go to definition and diagnostics support

### ISSUE THREAD

**Issue by vladyadubrovsky** [CppCXY/Intellij-SumnekoLua#1]
Do you plan to support GoToDefinition and other stuff? Or is still lack of support from JetBrains?

From the post https://blog.jetbrains.com/platform/2023/07/lsp-for-plugin-developers/
- lspGoToDefinitionSupport
- lspDiagnosticsSupport
- lspCodeActionsSupport

**Comment by CppCXY** [comment]
All features are already supported. The entire plugin is designed to launch SumnekoLua. If there are any bugs in certain features, it is because JetBrains' support may not be sufficient.

**Comment by CppCXY** [comment]
he "goto Definition" feature is not reflected in the right-click mouse menu. You need to use Ctrl + left-click to access it. As for code diagnostics, you can directly see them. For code actions, some quick fixes are available, but JetBrains has not implemented the executeCommand, which means that more quick fixes cannot be used yet.

**Comment by CppCXY** [comment]
It's possible that you're not using Windows. By default, Mac doesn't have execution permissions. 
and jetbrain hasn't implemented the hover protocol.
