### ISSUE TITLE
Support Plan

### ISSUE THREAD

**Issue by CppCXY** [CppCXY/Intellij-SumnekoLua#2]
## Completed
- [x] Support text synchronization
- [x] Support code completion
- [x] Support code navigation
- [x] Support code refactoring
- [x] Support code formatting since 2023.3
- [x] Support code diagnostics
- [x] Support document hover since 2023.3.2
- [x] Support execute command since 2024.1 EAP6
- [x] Optimize highlighting

## In Progress
- [ ] Support symbol search
- [ ] Plugin system
- [ ] References

## Maybe
- [ ] Debugger

**Comment by pitermcflebor** [comment]
@CppCXY the "In Progress" section mention the "Support symbol search" this means the `.luarc.json` file with some libraries defined doesn't work?
For me is not working. Maybe you want me to open an issue

**Comment by CppCXY** [comment]
his feature is used to find symbols in the double shift search in intellij. The reading and watching of .luarc entirely depends on luals itself. If it doesn't work correctly for you, you can check the configuration documentation in the wiki of luals.

**Comment by pitermcflebor** [comment]
> this feature is used to find symbols in the double shift search in intellij. The reading and watching of .luarc entirely depends on luals itself. If it doesn't work correctly for you, you can check the configuration documentation in the wiki of luals.

I tried to search why is not working. I'm using Rider IDE and I just opened a folder containing Lua files, then I created the luarc json file and added the "workspace.library" setting but it doesn't suggest anything.
Can you guide me or how can I know if the LuaLS is loading the luarc file?

**Comment by CppCXY** [comment]
![image](https://github.com/CppCXY/Intellij-SumnekoLua/assets/40318218/8b7c7369-99ce-475d-b9ae-8740192b96bf)
it work well for me.
Is it an operating system issue that you can't really start luals? You can check if you have the lua-language-server process running.
