### ISSUE TITLE
AutoComplete seems not IntelliJ compatible

### ISSUE THREAD

**Issue by boppy** [CppCXY/Intellij-SumnekoLua#4]
Auto completion suggestions are working, but as soon as I tab/enter to start it, the complete output is generated, but the jump marks are not accessible.

The Output is:
![image](https://github.com/CppCXY/Intellij-SumnekoLua/assets/749141/5fd736ba-dd93-4405-a247-d20934933baf)

I always end up at the "end". 

Is this a config thing or a plugin problem? I'm happy to help, if  you need someone to test/debug something...

|||
| --- | --- |
| Plugin-Version | 3.6.23.7-IDEA232 |
| IntelliJ Platform | phpStorm |
| PhpStorm Version | 2023.2.3 |
| PhpStorm Build | Build #PS-232.10072.32 |
| Platform | Linux |

**Comment by CppCXY** [comment]
This is because jetbrain's implementation of the lsp protocol in version 2023.2 was very incomplete, and this feature has been implemented in 2023.3. 
2023.3 also implements the formatting protocol. But the hover protocol will not be available until 2023.3.1. You can try the new version by upgrading to the 2023.3 beta.

**Comment by boppy** [comment]
Okay, after updating to PhpStorm 2023.3 Bete (Build #PS-233.11799.21) I see that the completion is one step closer.

But still the jump marks do not really work. I jump to the first one, but after entering it, a `ENTER` or `TAB` does not make it iterate. It works on single-input without auto-complete, like `if`, but seems not to work with `for ipairs` for example. As soon as I pick something from auto-complete it looses its state...

If I escape the auto-complete by pressing `ESC` I can jump to the next point...

https://github.com/CppCXY/Intellij-SumnekoLua/assets/749141/b31f7767-7197-4703-a383-ef68cb4bf66c

**Comment by CppCXY** [comment]
Currently the official jetbrain lsp implementation is still not perfect, every version of the update 1 or 2 features, and in terms of intellij platform, its psi-based analysis system still has a great advantage, this plugin is just my attempt to port the language server, in fact, there are still a very large number of work to be accomplished by psi, such as code folding, highlighting, bracket matching, etc. ...

intellij platform lua plug-ins in the most complete is still emmylua, if it is for a better coding experience, it is best to choose emmylua, and even this plug-in itself is based on emmylua castration change over!

**Comment by boppy** [comment]
> It's a problem with the implementation of jetbrain itself, you can submit this issue to youtrack

As you stated that Jetbrains is still heavily working on support of LSP, I assume that those limits are well known. So I'll not open a ticket on youtrack for that...

> intellij platform lua plug-ins in the most complete is still emmylua, if it is for a better coding experience, it is best to choose emmylua, and even this plug-in itself is based on emmylua castration change over!

Thank you for that recommendation (and your open words about the state of this plugin!). I thought that LSP is more reliable, because it's a well-known and not-so-young way to interact... But I seem to be wrong - at least regarding JetBrains adoption ;) - So I'll go with emmylua for the time being. But I'll check your plugin from time to time to see, if it's the better option in the future!

**Comment by boppy** [comment]
That sounds really good, tbh. As long as I don't need to f*** around with Java, I'm all in for some lua-testing, so just ping (@boppy) me if you need somebody to test something... ;)

I can provide with Linux testing primarily, but can also check things on my Windows (currently 10) machine, if needed. I have an all products licence from JetBrains, so I can also test on different apps.

**Comment by CppCXY** [comment]
intellij-Sumneko Lua has been updated to the LSP4IJ implementation, supporting most features in LSP.
