### ISSUE TITLE
plugin make idea Code completion fail

### ISSUE THREAD

**Issue by echo1937** [CppCXY/Intellij-SumnekoLua#5]
The plugin will cause Java's error reporting functionality for missing semicolons, braces, etc. to become ineffective.

IDEA 2023.3.4
version 3.7.3.19-IDEA233

**Comment by CppCXY** [comment]
Can you post the error?

**Comment by CppCXY** [comment]
you can update from https://github.com/CppCXY/Intellij-SumnekoLua/actions/runs/8258447485
but is just for 2024.1
