### ISSUE TITLE
Can't comment out Lua code

### ISSUE THREAD

**Issue by kodra-dev** [CppCXY/Intellij-SumnekoLua#6]
![image](https://github.com/CppCXY/Intellij-SumnekoLua/assets/117553001/52fe2a99-9170-48a8-9af2-8eeb4419cbe5)

It seems like in Lua files, the "Comment with..." actions are greyed out. Is this supported yet?

**Comment by CppCXY** [comment]
Currently there is no support, maybe I missed it, although it is a language server plugin, but many front-end functions still need to use psi to complete

**Comment by CppCXY** [comment]
I've implemented this feature, and you can download it from github action later.
